#!/bin/sh
export DB_POSTGRESDB_HOST=${PGHOST}
export DB_POSTGRESDB_PORT=${PGPORT}
export DB_POSTGRESDB_USER=${PGUSER}
export DB_POSTGRESDB_PASSWORD=${PGPASSWORD}
export DB_POSTGRESDB_DATABASE=${PGDATABASE}
exec n8n start
